// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqzlO-esRKaKjcLYzsZlstcnnXHfq-wY',
    appId: '1:33860724078:web:fa9e4fcd254717f5028d7f',
    messagingSenderId: '33860724078',
    projectId: 'yatzi-3f690',
    authDomain: 'yatzi-3f690.firebaseapp.com',
    storageBucket: 'yatzi-3f690.firebasestorage.app',
    measurementId: 'G-0K4R9Q6QPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIsUfo3BoBejRPeOXVsJCXYgda1kelkM',
    appId: '1:33860724078:android:0f17bd6bf658a034028d7f',
    messagingSenderId: '33860724078',
    projectId: 'yatzi-3f690',
    storageBucket: 'yatzi-3f690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbL030Y3RvpeBHPuq7hzFfNX0U6KUkG8',
    appId: '1:33860724078:ios:107e859e65d11a14028d7f',
    messagingSenderId: '33860724078',
    projectId: 'yatzi-3f690',
    storageBucket: 'yatzi-3f690.firebasestorage.app',
    iosBundleId: 'com.yatzy.yatzyMultiplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbL030Y3RvpeBHPuq7hzFfNX0U6KUkG8',
    appId: '1:33860724078:ios:107e859e65d11a14028d7f',
    messagingSenderId: '33860724078',
    projectId: 'yatzi-3f690',
    storageBucket: 'yatzi-3f690.firebasestorage.app',
    iosBundleId: 'com.yatzy.yatzyMultiplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqzlO-esRKaKjcLYzsZlstcnnXHfq-wY',
    appId: '1:33860724078:web:39900f6baca20059028d7f',
    messagingSenderId: '33860724078',
    projectId: 'yatzi-3f690',
    authDomain: 'yatzi-3f690.firebaseapp.com',
    storageBucket: 'yatzi-3f690.firebasestorage.app',
    measurementId: 'G-P8WY2NY2H8',
  );
}
